Passing time in sky
DSF256/godot-demo-projects pull request #7
Opened 2020-04-12 11:30 UTC by mbagwell

This commit gives the illusion that time is passing by making the sky and clouds fade and reappear over time.

2020-04-14 23:25 UTC, WilltheWys reviewed
Adding these changes makes the background look a little more pleasing. Making the Background Dynamic and changing is more pleasing to the eyes. It makes everything look like its moving.

2020-04-16 02:35 UTC, NotHacker101 approved these changes
I like that you explain what you did in a short way !!! keep up the good work.

2020-04-16 17:56 UTC, DSF256 commented
This looks pretty cool; a day and night transition makes the game feel a lot more lively.  I would probably recommend making the day/night cycle transitions somewhat longer, though.  The sky changes every 1 second, which makes days go by a bit too quickly.  I would probably change it to once every 5 or 6 seconds.

2020-04-16 18:10 UTC, DSF256 requested changes
Okay, I think I screwed that last one up.  Anyway, I think this is good save for the interval between sky changes.  I tested a 5-second interval in my own project, and it seemed to feel more natural.  Hope this helps.

2020-04-17 12:11 UTC, reid-wynkoop commented on 2d/platformer/src/Level/Sky.gd
> +onready var sprite = $Sprite
does sprite ever get used?

2020-04-17 12:13 UTC, reid-wynkoop approved these changes

2020-04-17 17:49 UTC, mbagwell commented on 2d/platformer/src/Level/Sky.gd
> +onready var sprite = $Sprite
No.

2020-04-20 13:51 UTC, merged